# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(567, 235)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(220, 10, 125, 30))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(220, 50, 125, 30))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setHidden(True)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_2.setGeometry(QtCore.QRect(220, 90, 125, 30))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_2.setHidden(True)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(220, 130, 125, 30))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.setHidden(True)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 170, 125, 30))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.setHidden(True)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(150, 170, 125, 30))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.setHidden(True)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(290, 170, 125, 30))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.setHidden(True)
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(430, 170, 125, 30))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_6.setHidden(True)
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(220, 170, 125, 30))
        self.pushButton_7.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 70, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.label.setHidden(True)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Защита информации Лаб. №1,3"))
        self.pushButton.setText(_translate("MainWindow", "Вход в систему"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Логин..."))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Пароль..."))
        self.pushButton_2.setText(_translate("MainWindow", "Войти"))
        self.pushButton_3.setText(_translate("MainWindow", "Смена пароля"))
        self.pushButton_4.setText(_translate("MainWindow", "Новый пользователь"))
        self.pushButton_5.setText(_translate("MainWindow", "Все пользователи"))
        self.pushButton_6.setText(_translate("MainWindow", "Выход"))
        self.pushButton_7.setText(_translate("MainWindow", "О программе"))
        self.label.setText(_translate("MainWindow", "Привет, пользователь!"))
